# -*- coding: utf-8 -*-                                                                                                                                                                                             
                                                                                                                                                                                                                    
import requests                                                                                                                                                                                                     
                                                                                                                                                                                                                    
TOKEN = "YOUR_TOKEN_HERE"                                                                                                                                                                          
                                                                                                                                                                                                                    
headers = {'Authorization': 'Token token=%s' % TOKEN}                                                                                                                                                               
                                                                                                                                                                                                                    
def getPorCEP(cep):                                                                                                                                                                                                 
    url = "http://www.cepaberto.com/api/v3/cep"                                                                                                                                                                     
    params = { 'cep': cep }                                                                                                                                                                                         
    json = requests.get(url, params=params, headers=headers).json()                                                                                                                                                 
    return json                                                                                                                                                                                                     
                                                                                                                                                                                                                    
def getPorCidade(uf, cidade, logradouro):                                                                                                                                                                           
    # Pesquisa de CEP por estado, cidade e logradouro                                                                                                                                                               
    url = "http://www.cepaberto.com/api/v3/address"                                                                                                                                                                 
    params = {'estado': uf, 'cidade': cidade, 'logradouro': logradouro}                                                                                                                                             
    json = requests.get(url, params=params, headers=headers).json()                                                                                                                                                 
    return json                                                                                                                                                                                                     
                                                                                                                                                                                                                    
def listaCidadesPorUf(uf):                                                                                                                                                                                          
    url = "http://www.cepaberto.com/api/v3/cities"                                                                                                                                                                  
    params = { 'estado' : uf }                                                                                                                                                                                      
    json = requests.get(url, params=params, headers=headers).json()                                                                                                                                                 
    return json                                                                                                                                                                                                     
                                                                                                                                                                                                                    
# Busca em um Raio de 10km                                                                                                                                                                                          
def getCEPMaisProximo(lat, lng):                                                                                                                                                                                    
    url = "http://www.cepaberto.com/api/v3/nearest"                                                                                                                                                                 
    params = { 'lat' : lat, 'lng': lng }                                                                                                                                                                            
    json  = requests.get(url, params=params, headers=headers).json()                                                                                                                                                
    return json           
